### ISSUE TITLE
[#feature_request] Unary and finitary math op

### ISSUE THREAD

**Issue by bachden** [dungba88/libra#1]
Plz add support for some common math ops:
- unary: like sqrt, sign
- ternary: like a ? b : c
- finitary: like avg(a0, a1..., an)

**Comment by dungba88** [comment]
SQRT and conditional operator has been supported f51e5d9d5ad3e5921f5ec081513f5669de365e3d

**Comment by dungba88** [comment]
Fixes #1, #3 (5d3bfc10bb026d0b40bdbeb5bb79222de2820bb6)
