### ISSUE TITLE
Update antlr4-runtime to version 4.10 or higher

### ISSUE THREAD

**Issue by Nickkreker** [dungba88/libra#6]
Latest versions of spring-boot-starter-data-jpa use antlr4-runtime with version 4.10.1. Breaking changes were made in [version 4.10](https://github.com/antlr/antlr4/releases/tag/4.10) (that require regeneration all of lexers and parsers) so it makes this library unusable with spring-boot-starter-data-jpa.

**Comment by dungba88** [comment]
Thanks @Nickkreker for reporting

Could you open a PR as well? For this type of change we also want to bumb the package version
